# SPDX-FileCopyrightText: 2024 Foundation Devices, Inc. <hello@foundationdevices.com>
# SPDX-License-Identifier: GPL-3.0-or-later

[workspace]
resolver = "2"

members = [
    "firmware",
    "bootloader",
    "host-protocol", "cobs-file-chuncker",
]
exclude = ["cobs-file-chunker"]

[profile.release]
debug = 2
