[package]
name = "cosign2-bin"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "cosign2"
path = "src/main.rs"

[dependencies]
chrono = "0.4"
clap = { version = "4.5", features = ["derive"] }
colored = "2.1"
cosign2 = { path = "../cosign2" }
hex = "0.4"
humansize = "2.1"
pem = "3.0"
sec1 = "0.7"
secp256k1 = "0.29"
semver = "1.0"
serde = { version = "1.0", features = ["derive"] }
tempfile = "3.10"
toml = "0.8"
sha2 = "0.10"
