name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install ARM target
      run: rustup target add thumbv7em-none-eabi
    - name: Build firmware
      run: cargo build --release --bin firmware
    - name: Build host-protocol
      run: cargo build --release --package host-protocol
