# SPDX-FileCopyrightText: 2024 Foundation Devices, Inc. <hello@foundation.xyz>
# SPDX-License-Identifier: GPL-3.0-or-later

name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: |
          ${{ secrets.SSH_KEY_DEPLOY_KEYOS }}
    - name: Install Ubuntu dependencies
      run: |
        sudo apt update
        sudo apt install -y llvm libclang-dev gcc-arm-none-eabi
    - name: Install ARM target
      run: rustup target add thumbv7em-none-eabi
    - name: Install Cargo binutils
      run: cargo install cargo-binutils
    - name: Install LLVM tools
      run: rustup component add llvm-tools
    - name: Build Debug image with S112 (unsigned)
      run: cargo xtask --verbose build-fw-debug-image
    - name: Build Debug image with S113 (unsigned)
      run: cargo xtask --verbose --s113 build-fw-debug-image
    - name: Build host-protocol
      run: cargo build --release --package host-protocol
